### ISSUE TITLE
存在问题及解决方案

### ISSUE THREAD

**Issue by mahailin** [mengxianliang/XLImageViewer#3]

**Comment by mahailin** [comment]
1、有两处循环引用，修改如下：
（1）、增加属性声明
@property (nonatomic, strong) UICollectionView *collectionView;
@property (nonatomic, strong) XLImageViewerTooBar *toolBar;
（2）、弱化引用
__weak __typeof(self) weakSelf = self;
    [cell addHideBlockStart:^{
        [weakSelf.toolBar hide];
    } finish:^{
        [weakSelf removeFromSuperview];
    } cancle:^{
        [weakSelf.toolBar show];
    }];
（3）、弱化引用
__weak __typeof(self) weakSelf = self;
    [_collectionView performBatchUpdates:nil completion:^(BOOL finished) {
        XLImageViewerItem *item = (XLImageViewerItem *)[weakSelf.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:index inSection:0]];
        [item showEnlargeAnimation];
    }];

   [[UIApplication sharedApplication].keyWindow addSubview:self];
2、当下拉图片后再上拉到contentoffset<0后放手，XLImageViewerTooBar界面不见了，修改如下：
在scrollViewPanMethod方法里修改    if (_scrollView.contentOffset.y > 0)
    {
        return;
    }
为
    if (_scrollView.contentOffset.y > 0)
    {
        _cancleideBlock();
        return;
    }
3、当下拉图片到contentoffset大于0小于100后放手，背景透明度有问题，修改如下：
增加如下方法：
- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    if (ABS(_scrollView.contentOffset.y) < minPanLength)
    {
        CGFloat alpha = 1 - ABS(_scrollView.contentOffset.y/(_scrollView.bounds.size.height));
        _collectionView.backgroundColor = [UIColor colorWithWhite:0 alpha:alpha];
    }
}

**Comment by mengxianliang** [comment]
你真的看的很仔细，谢谢你提出的问题，已经改好了。
